### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by RiffRaff4469** [CosmodiumCS/MK01-OnlyRAT#1]
After installing and restarting terminal it says command not found when I type onlyrat. Am I doing something wrong?

**Comment by PrettyBoyCosmo** [comment]
are u using a bash terminal? i'll make updates for people using ash and such

**Comment by NyxKazuya** [comment]
the same goes for me

**Comment by PrettyBoyCosmo** [comment]
i added ZSH support, should work for y'all now :D
