### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Fydren** [CosmodiumCS/MK01-OnlyRAT#6]
Can someone please help me set this up so I can hit some licks

**Comment by wyrdCCS** [comment]
My brother in Christ. There is a README.md that will tell you what you need. May Frong guide you.

**Comment by Soulsender** [comment]
Only [Frong](https://www.youtube.com/watch?v=wS9yOYWn2ZY&list=PLqivV57hkUuxIUr_HzugZBBuabLr5cv5g&index=1) can help him now...

**Comment by wyrdCCS** [comment]
@Fydren please read this https://github.com/CosmodiumCS/MK01-OnlyRAT. If you have any problems please join the discord so we can help. I am going to close this. This is not for skill issues.
