### ISSUE TITLE
scp: /home/USER/*.rat: No such file or directory

### ISSUE THREAD

**Issue by marshmadnesss** [CosmodiumCS/MK01-OnlyRAT#7]
It looks like the VPS isnt pulling the data from the target machine. Followed the documentation and YT video exactly. VPS is an Ubuntu 22.04

**Comment by PrettyBoyCosmo** [comment]
hey! thanks for reaching out. the code should be working so it is likely a networking issue or a logical error.

- go on your VPS and see if the key file was even successfully uploaded
- check the scripts and OnlyRAT console to make sure the VPS IP and Username were correctly inputted
- also make sure you enabled BOTH `AllowTcpForwarding` and `GatewayPorts` on your VPS

any screenshots and error messages would be greatly appreciated for troubleshooting.

**Comment by marshmadnesss** [comment]
Here is screenshots from the VPS side (VPS is Ubuntu 22.04 on Linode)

from-vps.cmd changes
![from-vps](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/41470e1e-eaf9-4e7a-843e-ff5d292c8f8f)

v1.cmd changes
![v1](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/9e8dca25-6be6-4f10-811d-457da587ba24)

v2.ps1 changes
![v2](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/f871e1ba-8afe-4081-8090-ab5f9c6570b1)

Target machine Powershell
![target machine 1](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/af592360-c571-4acf-a16c-0b38ef07905b)

This is what the VPS shows running sudo pthon3 -m http.server 80
![VPS server side](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/b8cd052a-00b8-4eb9-82ef-c89478146ac6)

Running onlyrat -d
![onlyrat -d](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/345f03eb-5e66-46e2-a0b6-23486058df77)

**Comment by rt-leaks** [comment]
![3d695aab-f261-4e16-82e8-f10df53ba63f](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/130487372/7379a9e6-284b-4d1d-b813-d845b063c10d)
uh dude.. you've forgotten to censore the IP in the big big red box here.

**Comment by marshmadnesss** [comment]
> ![3d695aab-f261-4e16-82e8-f10df53ba63f](https://private-user-images.githubusercontent.com/130487372/294281283-7379a9e6-284b-4d1d-b813-d845b063c10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTczNDIsIm5iZiI6MTcwNDM5NzA0MiwicGF0aCI6Ii8xMzA0ODczNzIvMjk0MjgxMjgzLTczNzlhOWU2LTI4NGItNGQxZC1iODEzLWQ4NDViMDYzYzEwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxOTM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTRmNTMzYzYzM2Y2NGNmMTU2YWE3NGRhMmE0NmE5MTRjOWYyNDAwZmZkNjEyZmRiZjM1MGIwMDljMDI3ODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WVrW8tCcIggCA5lbIBDcZXXdZmgroMBLuxOvoAGo3Vc) uh dude.. you've forgotten to censore the IP in the big big red box here.

WHOOPS! LOL missed one thanks for that! Good thing its a "throw away" vps lol

**Comment by PrettyBoyCosmo** [comment]
@marshmadnesss 
don't run onlyrat as root, you almost never run applications with root perms. especially not a malware from the internet haha!

try the install process again as a normal user on the vps. the screenshot says that they key was successfully uploaded. so you can probably download it manually with

```bash
scp -r ad06@X.X.X.X:~/user.rat .
```

**Comment by marshmadnesss** [comment]
Heres screenshots
AllowTCP is yes and Gateway Ports is yes

from-vps.cmd
![from-vps](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/7e32c153-74cb-4d10-b198-cdba5ed3b262)

v1.cmd
![v1](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/254c6f75-1a3b-4d16-88f3-d79f323a7213)

v2.ps1
![v2](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/cc6ff48a-6458-4dfe-a5eb-8b2fa6ede72f)

target machine
![target machine 1](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/6a3d92cf-10fa-4f85-911c-12d36119664e)

server side shows this after running from-vps.cmd
![VPS server side](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/34094f38-2223-4d74-86a8-e995728da4d8)

onlyrat -d then shows this
![onlyrat -d](https://github.com/CosmodiumCS/MK01-OnlyRAT/assets/28793022/d7bf3ddf-5745-4420-ba8d-bee7612acad3)

**Comment by PrettyBoyCosmo** [comment]
> @marshmadnesss don't run onlyrat as root, you almost never run applications with root perms. especially not a malware from the internet haha!
> 
> try the install process again as a normal user on the vps. the screenshot says that they key was successfully uploaded. so you can probably download it manually with
> 
> ```shell
> scp -r ad06@X.X.X.X:~/user.rat .
> ```

☝🏽️

**Comment by marshmadnesss** [comment]
> > @marshmadnesss don't run onlyrat as root, you almost never run applications with root perms. especially not a malware from the internet haha!
> > try the install process again as a normal user on the vps. the screenshot says that they key was successfully uploaded. so you can probably download it manually with
> > ```shell
> > scp -r ad06@X.X.X.X:~/user.rat .
> > ```
> 
> ☝🏽️

AhhH! Right! That was my issue! Works great now!

**Comment by PrettyBoyCosmo** [comment]
no worries, glad it worked out :D
